spring:
  datasource:
    url: jdbc:mysql://localhost:3307/recipe_dev
    username: dev_user
    password: recipe
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    show-sql: true