spring:
  datasource:
    url: jdbc:mysql://localhost:3307/recipe_dev
    username: dev_user
    password: recipe
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          delimiter: ";"
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: database_create.sql
  sql:
    init:
      mode: always
      platform: mysql